web0:
  build: .
  container_name: web0
  ports:
    - "8000:80"
  volumes:
    - ./Code/web0:/var/www
    - ./logs/web0/nginx:/var/log/nginx
    - ./settings/web0/nginx:/etc/nginx/sites-available
  links:
#    - web1
#    - web3
    - mysql1
    - mysql2
    - mysql3
    - redis1
  privileged: true

web1:
  image: tkcdocker/php56nginx
  container_name: web1
  ports:
    - "8001:80"
  volumes:
    - ./Code/web1:/var/www
    - ./logs/web1/nginx:/var/log/nginx
    - ./settings/web1/nginx:/etc/nginx/sites-available
  links:
    - web0
#    - web1
    - web2
    - web3
    - mysql1
    - mysql2
    - mysql3
    - redis1
  privileged: true

web2:
  image: tkcdocker/php56nginx
  container_name: web2
  ports:
    - "8002:80"
  volumes:
    - ./Code/web2:/var/www
    - ./logs/web2/nginx:/var/log/nginx
    - ./settings/web2/nginx:/etc/nginx/sites-available
  links:
    - mysql1
    - mysql2
    - mysql3
    - redis1
  privileged: true

web3:
  image: tkcdocker/php56nginx
  container_name: web3
  ports:
    - "8003:80"
  volumes:
    - ./Code/web3:/var/www
    - ./logs/web3/nginx:/var/log/nginx
    - ./settings/web3/nginx:/etc/nginx/sites-available
  links:
#    - web0
#    - web1
#    - web2
    - mysql1
    - mysql2
    - mysql3
    - redis1
  privileged: true

mysql1:
  image: mysql:latest
  container_name: mysql1
  ports:
    - "3316:3306"
  volumes_from:
    - data-mysql1
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: N
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
  privileged: true

mysql2:
  image: mysql:latest
  container_name: mysql2
  ports:
    - "3317:3306"
  volumes_from:
    - data-mysql2
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: N
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
  privileged: true

mysql3:
  image: mysql:latest
  container_name: mysql3
  ports:
    - "3318:3306"
  volumes_from:
    - data-mysql3
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: N
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
  privileged: true

redis1:
  image: laradock/redis:latest
  container_name: redis1
  ports:
    - "6380:6379"
  volumes_from:
    - data-redis1
  restart: always
  privileged: true

data-mysql1:
  image: busybox
  container_name: data-mysql1
  volumes:
    - /var/lib/mysql

data-mysql2:
  image: busybox
  container_name: data-mysql2
  volumes:
    - /var/lib/mysql

data-mysql3:
  image: busybox
  container_name: data-mysql3
  volumes:
    - /var/lib/mysql

data-redis1:
  image: busybox
  container_name: data-redis1
  volumes:
    - /var/lib/mysql

