FROM tkcdocker/laravel-mongo
MAINTAINER tkc <info@onga.jp>

RUN \
    apt-get install python-software-properties\
    add-apt-repository ppa:ondrej/php\
    sudo apt-get purge php5\
    sudo apt-get update\
    sudo apt-get install php\
    apt-get --purge autoremove \
    apt-get install php7.0-fpm php7.0-mysql php7.0-curl php7.0-gd php7.0-json php7.0-mcrypt php7.0-opcache php7.0-xml php7.0-readline php7.0-cli
    apt-get install redis-server\
    apt-get install php7-redis\
    apt-get install rpm\

RUN \
    php --version\
    service php7.0-fpm start


#php70-runtime-1.0-1.el6.remi.x86_64
#php70-php-common-7.0.4-1.el6.remi.x86_64
#php70-php-7.0.4-1.el6.remi.x86_64
#php70-php-bcmath-7.0.4-1.el6.remi.x86_64
#php70-php-pdo-7.0.4-1.el6.remi.x86_64
#php70-php-gd-7.0.4-1.el6.remi.x86_64
#php70-php-fpm-7.0.4-1.el6.remi.x86_64
#php70-php-pear-1.10.1-4.el6.remi.noarch
#php70-php-pecl-redis-2.2.8-0.5.20160215git2887ad1.el6.remi.x86_64
#php70-php-json-7.0.4-1.el6.remi.x86_64
#php70-php-cli-7.0.4-1.el6.remi.x86_64
#php70-php-mbstring-7.0.4-1.el6.remi.x86_64
#php70-php-mysqlnd-7.0.4-1.el6.remi.x86_64
#php70-php-xml-7.0.4-1.el6.remi.x86_64
#php70-php-devel-7.0.4-1.el6.remi.x86_64
#php70-php-process-7.0.4-1.el6.remi.x86_64
#php70-php-pecl-igbinary-1.2.2-0.1.20151217git2b7c703.el6.remi.x86_64


